branch-defaults:
  master:
    environment: synaptify
    group_suffix: null
global:
  application_name: synaptify
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
